config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :charges

  root 'home#index'

  get 'home/index'
  get 'developers'          => 'developers#index'
  get 'contact'             => 'contact#index'
  get 'games'               => 'games#index'
  get 'games/coming_soon'   => 'games#coming_soon'
  get 'play_game/:id'       => 'games#play_game'
  post 'play_game/add_comment'    => 'games#add_comment'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create

    # Get the donation amount in cents
    @amount = params[:amount]

    @amount = @amount.gsub('$', '').gsub(',', '')

    begin
      @amount = Float(@amount).round(2)
    rescue
      flash[:error] = 'Charge not completed. Please enter a valid amount in USD ($).'
      redirect_to new_charge_path
      return
    end

    @amount = (@amount * 100).to_i # Must be an integer!

    if @amount < 500
      flash[:error] = 'Charge not completed. Donation amount must be at least $5.'
      redirect_to new_charge_path
      return
    end



    #create the customer object
    customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
    )

    #charge the card
    #create the charge object
    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount => @amount,
        :currency    => 'cad',
        :description => 'custom donation',
        :source => params[:stripeToken]

    )
    charge = Stripe::Charge.retrieve("ch_1A9eP02eZvKYlo2CkibleoVM")
    charge.capture

    #get paid
    #create the payout object
    payout = Stripe::Payout.create(
        :amount => @amount,
        :currency => "cad",
    )

    #create purchase object
    # to keep track of purchases
    purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken],
                               amount: @amount, description: product.description, currency: "cad",
                               customer_id: customer.id, product_id: product.id, uuid: SecureRandom.uuid)
    redirect_to purchase


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:play_game]
  before_action :retrieve_comments, only: [:play_game]

  def index
    @games = Game.all
  end

  def play_game
    if !(@game.fund_goal)
      redirect_to '/games/coming_soon'
    end
  end

  def add_comment
    @comment = Comment.new(comment_params)
    @comment.save
    if @comment.reply == nil
      Comment.update(@comment.id, :reply => @comment.id)
    end
    redirect_to "/play_game/#{@comment.game}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_game
      @game = Game.find(params[:id])
    end

    def retrieve_comments
      @comments = Comment.where(game: params[:id]).order(:reply, :created_at)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :game, :author, :reply)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/index.html.erb
<div class="row" id="contact-content">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="page-content">
      <h1 class="page-title">Contact</h1>
      <p>
        This project was developed for the final project of the class Comp 307 (Principles of Web Development) at McGill University in Fall 2017. It is based on the Ruby On Rails framework.
      </p>
      <h3>Authors</h3>
      <p>
        <b>Isabelle Grégoire</b><br>
        isabelle.gregoire3@mail.mcgill.ca<br>
        <b>Simon Fredette</b><br>
        simon.fredette@mail.mcgill.ca<br>
        <b>Arjun B. Gupta</b><br>
        boris.gupta@mail.mcgill.ca<br>
      </p>
    </div>
  </div>
</div>

app/views/developers/index.html.erb
<div class="row" id="contact-content">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="page-content">
      <h1 class="page-title">Developers</h1>
      <p>
        This page is for people wanting to upload their own game to our platform and get some funding.
      </p>
      <p>
        For security reasons, we cannot let you upload a javascript file straight to our server at this time. We are working on way to solve this issue. In the meantime, we suggest that you get in touch with our support team:
      </p>
      <p><b>support@gamechanger.com</b></p>
    </div>
  </div>
</div>

app/views/games/coming_soon.html.erb
<div class="row" id="contact-content">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="page-content">
      <h1 class="page-title">/!\ Game Not Available /!\</h1>
      <p>
        Sorry, the game you're trying to access has not yet been developed. Be patient, the dev is planning on releasing it soon!
      </p>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div id="game-gallery" class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h1 class="page-title">Games</h1>
    <% @games.each do |game| %>
        <div class="responsive">
          <div class='gallery'>
            <a href="play_game/<%= game.id %>">
              <%= image_tag(game.name+'.png', alt: game.name, size:'256x256') %>
            </a>
            <div class="desc"><%= game.display_name %></div>
          </div>
        </div>
    <% end %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/games/play_game.html.erb
<script>
  function changeReply(reply,author) {
      $('#reply-input').val(reply);
      if (reply != "") {
          $('#response-to').text(author);
          $('#response-msg').show();
      } else {
          $('#response-msg').hide();
      }
  }
</script>

<div class="row" id="play-game">
  <div class="col-sm-6 col-sm-offset-1">
    <canvas width="600" height="600" style="background-color: black" id="screen-<%= @game.name %>" class="game-canvas"></canvas>
    <%= javascript_include_tag "#{@game.name}.js" %>
  </div>
  <div class="col-sm-4">
    <div id="game-funding-info">
      <h3><%= @game.display_name %></h3>
      <div id="progress-bar">
        <div id="completed"></div>
      </div>
      <div class="main-info" id="current-fund">$<%= @game.current_fund %></div>
      <div class="text-labels">pledged of the $<%= @game.fund_goal %> goal</div>
      <div class="main-info"><%= @game.nmb_backers %></div>
      <div class="text-labels">backers</div>
      <div class="main-info" id="days-left"></div>
      <div class="text-labels">days to go</div>
      <div id="funding-box">
        <div id="backing-button">Back this project</div>
        <!-- Stripe -->
        <%= form_tag charges_path, id:'chargeForm' do %>

            <!-- display errors -->
            <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
            <% end %>

            <!-- form fields -->
            <article>
              <%= label_tag(:amount, 'Donation Amount:') %><br>
              <%= text_field_tag(:amount) %>
            </article>
            <%= hidden_field_tag 'stripeToken' %>
            <%= hidden_field_tag 'stripeEmail' %>
            <%= hidden_field_tag 'amount', 500 %>

            <!-- button launches form -->
            <button id='donateButton' type="button" class="btn btn-success">Sponsor this game!</button>

            <!-- necessary scripts for the form submit-->
            <script src="https://checkout.stripe.com/checkout.js"></script>

            <script>

                //handler object is configured with a few options, including the public API key and a call back for the token.
                var handler = StripeCheckout.configure({
                    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                    locale: 'auto',
                    name: 'Be A Game Changer',
                    description: 'Sponsor this game',
                    token: function(token, arg) {
                        document.getElementById("stripeToken").value = token.id;
                        document.getElementById("stripeEmail").value = token.email;
                        document.getElementById("chargeForm").submit();
                    }
                });

                //when the user clicks on the button,
                //the javascript verifies the amount specified and
                //if valid, launches the chekout.
                $('#donateButton').on('click', function(e) {
                    e.preventDefault();

                    $('#error_explanation').html('');

                    var amount = $('input#amount').val();
                    amount = amount.replace(/\$/g, '').replace(/\,/g, '')

                    amount = parseFloat(amount);

                    if (isNaN(amount)) {
                        $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
                    }
                    else if (amount < 5.00) {
                        $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
                    }
                    else {
                        amount = amount * 100; // Needs to be an integer!
                        handler.open({
                            amount: Math.round(amount)
                        })
                    }
                });

                // Close Checkout on page navigation
                $(window).on('popstate', function() {
                    handler.close();
                });

            </script>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row" id="comment-section">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="page-content">
      <h1>Comments</h1>

      <% if @comments.length != 0 %>
        <% @comments.each do |c| %>
              <div class="row">
                <% if c.reply == c.id %>
                  <div class="col-sm-12">
                    <div class="row comments">
                          <div class="col-sm-2 auth">
                            <%= image_tag('pp.jpg', alt: c.author, size:'25x25') %>
                            <span class="author"><%= c.author %></span>
                            <div class="comment-date">
                              <%= c.created_at %>
                            </div>
                          </div>
                          <div class="com-separation"></div>
                          <div class="col-sm-9">
                            <%= c.text %><br>
                            <button type="button" onclick="changeReply('<%= c.reply %>','<%= c.author %>')">Reply</button>
                          </div>
                    </div>
                  </div>
                <% else %>
                  <div class="col-sm-11 col-sm-offset-1">
                    <div class="row comments">
                      <div class="col-sm-3 auth">
                        <%= image_tag('pp.jpg', alt: c.author, size:'25x25') %>
                        <span class="author"><%= c.author %></span>
                        <div class="comment-date">
                          <%= c.created_at %>
                        </div>
                      </div>
                      <div class="com-separation"></div>
                      <div class="col-sm-8">
                        <%= c.text %><br>
                        <button type="button" onclick="changeReply('<%= c.reply %>','<%= c.author %>')">Reply</button>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
        <% end %>
      <% else %>
        <div class="row">
          <div class="col-sm-12">
            Nobody has commented on this game yet.
          </div>
        </div>
      <% end %>

      <div id="response-msg">(In response to <span id="response-to"></span>)
        <button onclick="changeReply('','')">Cancel</button><br>
      </div>
      <form action="/play_game/add_comment" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <textarea placeholder="Write a comment here" name="comment[text]" rows="3" cols="80"  id="comment" ></textarea><br>
        <input type="hidden" name="comment[game]" value="<%= @game.id %>">
        <% if user_signed_in? %>
          <input type="hidden" name="comment[author]" value="<%= current_user.name %>">
        <% end %>
        <input type="hidden" name="comment[reply]" value="" id="reply-input">
        <input type="submit" value="Send">
      </form>
    </div>
  </div>
</div>

<script>
  //remove scrolling with space bar
    $(document).keydown(function(e) {
        if (e.which == 32 && e.target == document.body) {
            e.preventDefault();
        }
    });

    reloadPage();
    loadProgressBar();
    loadDaysLeft();

    $(document).ready(function(){
        $('#backing-button').click(function(){
            $('#chargeForm').slideToggle();
        });
    });

    function reloadPage() {
        if(!window.location.hash) {
            window.location = window.location + '#loaded';
            window.location.reload();
        }
    }

    function loadProgressBar() {
        var fund_goal = parseInt("<%= @game.fund_goal %>");
        var fund = parseInt("<%= @game.current_fund %>");
        var completed_width = (fund / fund_goal) * $('#progress-bar').width();
        $('#completed').animate({
            width: completed_width
        }, 2000 );
    }

    function loadDaysLeft() {
        var current = moment();
        var last = moment("<%= @game.created_at %>".replace(' UTC','')).add(parseInt("<%= @game.nmb_backers %>"),'d');
        var days_left = current.diff(last, 'days') + 1;
        $('#days-left').text(days_left);
    }
</script>

app/views/home/index.html.erb
<div id="index-main">
  <div id="main-text">
    <h1>Every developer started somewhere.</h1>

    <h3>
      We help game developers fund themselves <br>
      and get feedback all thanks to our amazing community of gamers.
    </h3>
    <div id="start-button"><a href="/games"><button type="button" class="btn btn-success btn-lg">Start Helping Now</button></a> </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GAMEChanger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'joystick.png', type: 'image/png' %>

  </head>

  <body>
    <div id="container" class="container-fluid">
      <header>
        <nav id="navbar">
          <div class="row" id="row-header">
            <div class="col-sm-2 col-sm-offset-1">
                <a id="home-btn" href="/">GAME|Changer</a>
            </div>
            <div class="col-sm-5 col-sm-offset-3">
              <table id="navmenu">
                <tr>
                  <td><a href="/">Home</a></td>
                  <td><a href="/games">Games</a></td>
                  <td><a href="/developers">Developers</a></td>
                  <td><a href="/contact">Contact</a></td>
                  <td>
                    <div class="dropdown" style="float:right;">
                      <button class="dropbtn">User</button>
                      <div class="dropdown-content">
                        <% if user_signed_in? %>
                            <div id="logged-in">Logged in as:<br><strong><%= current_user.email %></strong></div>
                            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        <% else %>
                            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        <% end %>
                      </div>
                    </div>
                  </td>
                </tr>
              </table>
            </div>
          </div>
          <span id="login">

          </span>
        </nav>
      </header>

      <main>
        <%= yield %>
      </main>

      <footer>
        GameChanger Inc. © 2017
      </footer>
    </div>
  </body>
</html>